baseURL = '/'
languageCode = 'en-us'
title = 'Neutron Studio'
theme = "terminal"

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[params]
  themeColor = "blue"
  centerTheme = true
  favicon = "/favicon.ico"
  readingTime = true

[params.twitter]
  creator = "pizzapanther"

[languages]
  [languages.en]
    languageName = "English"
    title = "Neutron Studio"
    copyright = ""

    [languages.en.params]
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      subtitle = "Web applications with cat logos"
      owner = ""
      keywords = ""
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      menuMore = "Show more"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"

    [languages.en.params.logo]
      logoText = "Neutron Studio"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/posts/"
      [[languages.en.menu.main]]
        identifier = "talks"
        name = "Talks"
        url = "/talks/"
      [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact"
